<script>
    const promise = new Promise((resolve, reject) => {
        resolve('foo')
    })

    promise.then(console.log)

    const promise1 = new Promise((resolve, reject) => {
        resolve('bar')
    })
    promise1
        .then((res) => {
            console.log(res)
            return 'baz'
        })
        .then((res) => {
            console.log(res)
        })

    Promise.resolve()
        .then(() => {
            // 使 .then() 返回一个 rejected promise
            throw new Error('Oh no!');
        })
        .then(() => {
            console.log('Not called.');
        }, error => {
            console.error('onRejected function called: ' + error.message);
        })
</script>