<script>
    const promise = new Promise((resolve, reject) => {
        reject('foo')
    })

    promise.catch((err) => {
        console.log(err)
    })
</script>